version: '3.3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "django_db"
      POSTGRES_USER: "django"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5433:5432"
  web:
    image: photojournal
    command: sh -c "
      sleep 10 &&
      echo 123 &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000 "
    ports:
      - "8000:8000"
    links:
      - "db:database"
    depends_on:
     - db
