# Generated by Django 4.0.4 on 2022-04-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photojournal', '0003_category_post_likes_profile_comments_post_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
