# Generated by Django 4.0.4 on 2022-04-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photojournal', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
