# Generated by Django 4.0.4 on 2022-04-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photojournal', '0005_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='project',
            new_name='post',
        ),
    ]
