# Generated by Django 4.0.4 on 2022-04-20 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photojournal', '0007_category_name_en_category_name_ru_comments_body_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name_ru',
        ),
    ]
